INSERT INTO
	T_ELDER(name, gero_id, nssf_id, archive_id, area_id, care_level, checkin_date, checkout_date, apply_url, survey_url, assess_url, track_url, pad_mac
)
VALUES
	('周云珠', '126', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
	,('李筱仙', '126', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
	,('顾阿囡', '126', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
	,('季英娣', '126', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
	,('周世伟', '126', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
	,('王慧英', '126', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
	,('袁采芸', '126', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
	,('袁春领', '126', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
	,('朱秀英', '126', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
	,('毛日暘', '126', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
	,('李义昌', '126', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
	,('周海宗', '126', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
	,('潘瑛', '126', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
	,('李传柱', '126', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
	,('叶凤英', '126', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
	,('金宝荪', '126', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
	,('张家法', '126', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
	,('龚旦', '126', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
	,('蒋阿义', '126', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
	,('杨阿泉', '126', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
	,('姚金林', '126', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
	,('徐惠英', '126', '', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL)
