INSERT INTO
	T_STAFF(name, nssf_id, gero_id, basic_url, leave_date, archive_id)
VALUES
	('admin', NULL, '126', NULL, NULL, NULL)
	,('周璟', '', '126', NULL, NULL, NULL)
	,('应裕生', '', '126', NULL, NULL, NULL)
	,('顾荣兰', '', '126', NULL, NULL, NULL)
	,('吴菊萍', '', '126', NULL, NULL, NULL)
	,('沈翠英', '', '126', NULL, NULL, NULL)
	,('桑云昆', '', '126', NULL, NULL, NULL)
	,('王成英', '', '126', NULL, NULL, NULL)
	,('林秀珍', '', '126', NULL, NULL, NULL)
	,('陈才珍', '', '126', NULL, NULL, NULL)
	,('曹莲香', '', '126', NULL, NULL, NULL)
	,('王八妹', '', '126', NULL, NULL, NULL)
	,('曹小风', '', '126', NULL, NULL, NULL)
	,('唐春莲', '', '126', NULL, NULL, NULL)
	,('肖仙', '', '126', NULL, NULL, NULL)
	,('张金英', '', '126', NULL, NULL, NULL)
	,('张新成', '', '126', NULL, NULL, NULL)
	,('杨玉兰', '', '126', NULL, NULL, NULL)
	,('陈晓菇', '', '126', NULL, NULL, NULL)
